# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Audit

on:
  
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4.0.3
      with:
        node-version: latest
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm audit