name: Auto-merge
on: pull_request

jobs:
  automerge:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || ((startsWith(github.event.pull_request.title, 'Bump to version ') || startsWith(github.event.pull_request.title, 'Update PNPM')) && (github.actor == 'github-actions' || github.actor == 'teh-hippo'))
    steps:
      - uses: actions/checkout@v4
      - run: gh pr merge --rebase --delete-branch --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ github.token }}