name: Auto-merge
on:
  workflow_dispatch:
  schedule:
    - cron: '37 13 * * 4'

permissions:
  contents: read
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AUTHOR: ${{ github.repository_owner }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Verify gh
        run: gh --version
      - name: Check it
        run: |
          find_pr() {
            author=$1
            term=$2
            echo "Looking for PRs from ${author} with '${term}' in the title"
            gh pr list --search "author:${author} '${term}'" --json number --jq '.[].number'
            for i in $(gh pr list --search "author:${author} '${term}'" --json number --jq '.[].number'); do
              echo gh pr merge -R ${{ github.repository }} --auto --rebase -d ${i}
            done
          }

          echo "Current PRs:"
          gh pr list --repo ${{ env.REPOSITORY }}
          echo "From author 0:"
          gh pr list --repo ${{ env.REPOSITORY }} --search "author:${{ env.AUTHOR }}"
          echo "From author 2:"
          gh pr list --repo ${{ env.REPOSITORY }} --search "author:${{ env.AUTHOR }} 'Update PNPM'"
          echo "From dependabot closed:"
          gh pr list --repo ${{ env.REPOSITORY }} --search "state:closed author:dependabot[bot] 'Bump'"
          echo "Are closed:"
          gh pr list --repo ${{ env.REPOSITORY }} --search "state:closed"
          echo "Are open:"
          gh pr list --repo ${{ env.REPOSITORY }} --search "state:open"

          echo "Looking for PRs to merge"
          find_pr 'dependabot[bot]' 'Bump'
          find_pr '${{ github.repository_owner }}' 'Update PNPM'