name: Auto-merge
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || ((startsWith(github.event.pull_request.title, 'Bump to version ') || startsWith(github.event.pull_request.title, 'Update PNPM')) && (github.actor == 'github-actions' || github.actor == 'teh-hippo'))
    steps:
      - run: gh pr merge --rebase --delete-branch --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}