name: Auto-merge
on:
  workflow_dispatch:
  schedule:
    - cron: '37 13 * * 4'

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    env:
      GITHUB_TOKEN: ${{ secrets.PR_PAT }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          find_pr() {
            author=$1
            term=$2
            for i in $(gh pr list -R '${{ github.repository }}' -A "${author}" --search "${term}" --json number --jq '.[].number'); do
              echo "Marking PR\#${i} to auto-merge"
              gh pr merge -R ${{ github.repository }} --auto --rebase -d ${i}
            done
          }

          find_pr 'dependabot[bot]' 'Bump'
          find_pr '${{ github.repository_owner }}' 'Update PNPM'
