name: Auto-merge
on:
  workflow_dispatch:
  schedule:
    - cron: '37 13 * * 4'

permissions:
  pull-requests: write

jobs:
  automerge:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          find_pr() {
            author=$1
            term=$2
            echo "Checking everything still exists:"
            gh pr list -R ${{ github.repository }} --json author,title,number
            echo "Looking for PRs from ${author} with '${term}' in the title"
            gh pr list -R '${{ github.repository }}' -A "${author}" --search "${term}" --json number --jq '.[].number'
            for i in $(gh pr list -R '${{ github.repository }}' -A "${author}" --search "${term}" --json number --jq '.[].number'); do
              gh pr merge -R ${{ github.repository }} --auto --rebase -d ${i}
            done
          }

          echo "Current PRs:"
          gh pr list -R ${{ github.repository }} --json author,title,number
          echo "From author:"
          gh pr list -R ${{ github.repository }} -A "${{ github.repository_owner }}" --json author,title,number
          echo "From author with term:"
          gh pr list -R ${{ github.repository }} -A "${{ github.repository_owner }}" --search "Update PNPM" --json author,title,number
          echo "From dependabot:"
          gh pr list -R ${{ github.repository }} -A "dependabot[bot]" --json author,title,number
          echo "From dependabot with term:"
          gh pr list -R ${{ github.repository }} -A "dependabot[bot]" --search "Bump" --json author,title,number

          echo "Looking for PRs to merge"
          find_pr 'dependabot[bot]' 'Bump'
          find_pr '${{ github.repository_owner }}' 'Update PNPM'
