# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update PNPM

on:
  
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    
permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      name: Cache node modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x
    - uses: pnpm/action-setup@v4
    - run: corepack up
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        delete-branch: true
        title: Update PNPM
        commit-message: |
          Update to the latest PNPM manager.
        token: ${{ secrets.PAT }}
        committer: AutoHippo <auto@hippo.org>
        branch: autohippo/update-pnpm-${{ github.run_number }}
